server:
  port: 8080

  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jdmd?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  thymeleaf: 
    mode: LECACYHTML5
    cache: false
  activemq:
    broker-url: tcp://localhost:61616
    #用户名
    user: admin
    #密码
    password: admin
    in-memory: true
    packages:
      trust-all: true
    pool:
      enabled: true